name: Deploy to Firebase Hosting

# Trigger workflow on pushes to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - uses: actions/checkout@v3

      # 2️⃣ Set up Firebase Hosting deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # GitHub token (automatically provided by Actions)
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # Firebase service account JSON secret (you must have added this secret)
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LYRICAL_BOLT_470510_G3 }}
          # Set the project ID explicitly to avoid "No currently active project" error
          projectId: lyrical-bolt-470510-g3
          # Deploy to the live channel
          channelId: live

